//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nesterce.rc
//
#define IDD_HELP_ABOUT                  103
#define IDR_MENU                        105
#define IDD_OPTIONS_CONTROLLERS         105
#define IDI_NESTERICON                  106
#define IDD_OPTIONS_GRAPHICS            107
#define IDD_OPTIONS_SOUND               108
#define IDD_OPTIONS_KEYPRESS            109
#define IDD_OPTIONS_DIRECTORY           110
#define IDR_TOOLBAR                     118
#define IDB_GAMEPAD                     121
#define IDR_PAD                         122
#define IDR_PAD_PNG                     124
#define IDD_OPTIONS_PREFERENCES         133
#define IDC_CHECK_SPEEDTHROTTLE         1000
#define IDC_RADIO_AUTOFRAMESKIP         1001
#define IDC_STATIC_KEY_A                1001
#define IDC_RADIO_FRAMESKIP             1002
#define IDC_STATIC_KEY_B                1002
#define IDC_STATIC_KEY_SELECT           1003
#define IDC_STATIC_KEY_START            1004
#define IDC_COMBO_THREADPRIORITY        1005
#define IDC_STATIC_KEY_UP               1005
#define IDC_COMBO_FRAMESKIP             1006
#define IDC_STATIC_KEY_DOWN             1006
#define IDC_DEFAULTS                    1007
#define IDC_STATIC_KEY_LEFT             1007
#define IDC_STATIC_KEY_RIGHT            1008
#define IDC_CHECK_SHOWSPRITES           1009
#define IDC_CHECK_SHOWALLSCANLINES      1010
#define IDC_CHECK_BLACKANDWHITE         1011
#define IDC_CHECK_CALCPALETTE           1012
#define IDC_SLIDER_TINT                 1014
#define IDC_SLIDER_HUE                  1015
#define IDC_RESET                       1016
#define IDC_CHECK_SOUNDENABLE           1017
#define IDC_COMBO_SAMPLERATE            1018
#define IDC_COMBO_SAMPLESIZE            1019
#define IDC_COMBO_FILTER                1020
#define IDC_COMBO_BUFFERLENGTH          1021
#define IDC_A                           1021
#define IDC_CHECK_RECTANGLE1            1022
#define IDC_B                           1022
#define IDC_CHECK_RECTANGLE2            1023
#define IDC_SELECT                      1023
#define IDC_CHECK_TRIANGLE              1024
#define IDC_START                       1024
#define IDC_ASSOCIATE                   1024
#define IDC_CHECK_NOISE                 1025
#define IDC_UP                          1025
#define IDC_UNDO                        1025
#define IDC_CHECK_DPCM                  1026
#define IDC_DOWN                        1026
#define IDC_RADIO_SRAM_ROMDIRECTORY     1026
#define IDC_CHECK_EXTERNAL              1027
#define IDC_LEFT                        1027
#define IDC_RADIO_SRAM_NESTERDIRECTORY  1027
#define IDC_RIGHT                       1028
#define IDC_EDIT_SRAM                   1028
#define IDC_CHECK_GAPI                  1029
#define IDC_LANDSCAPE                   1030
#define IDC_SHOW_FPS                    1030
#define IDC_DEL_A                       1031
#define IDC_RADIO_SAVESTATE_ROMDIRECTORY 1031
#define IDC_DEL_B                       1032
#define IDC_RADIO_SAVESTATE_NESTERDIRECTORY 1032
#define IDC_DEL_SELECT                  1033
#define IDC_EDIT_SAVESTATE              1033
#define IDC_DEL_START                   1034
#define IDC_DEL_UP                      1035
#define IDC_DEL_DOWN                    1036
#define IDC_DEL_LEFT                    1037
#define IDC_DEL_RIGHT                   1038
#define IDC_ALT_KEYSCAN                 1039
#define IDM_FILE                        40007
#define IDS_FILE                        40008
#define IDM_FILE_OPEN                   40009
#define IDM_FILE_CLOSE                  40010
#define IDM_FILE_EXIT                   40011
#define IDM_OPTIONS                     40012
#define IDS_OPTIONS                     40013
#define IDM_HELP                        40014
#define IDS_HELP                        40015
#define IDM_FILE_RESET                  40016
#define IDM_FILE_ROMINFO                40017
#define IDM_FILE_RESUME                 40018
#define IDM_FILE_LOAD_STATE             40019
#define IDM_FILE_SAVE_STATE             40020
#define IDM_FILE_QUICK_SAVE             40021
#define IDM_FILE_QUICK_LOAD             40022
#define IDM_FILE_SLOT_0                 40023
#define IDM_FILE_SLOT_1                 40024
#define IDM_FILE_SLOT_2                 40025
#define IDM_FILE_SLOT_3                 40026
#define IDM_FILE_SLOT_4                 40027
#define IDM_FILE_SLOT_5                 40028
#define IDM_FILE_SLOT_6                 40029
#define IDM_FILE_SLOT_7                 40030
#define IDM_FILE_SLOT_8                 40031
#define IDM_FILE_SLOT_9                 40032
#define IDM_HELP_ABOUT                  40033
#define IDM_OPTIONS_PREFERENCES         40037
#define IDM_OPTIONS_GRAPHICS            40038
#define IDM_OPTIONS_SOUND               40039
#define IDM_OPTIONS_CONTROLLERS         40040
#define IDM_OPTIONS_LANDSCAPE           40041
#define IDM_OPTIONS_DIRECTORY           40043
#define IDM_OPTIONS_FULLSCREEN          40044
#define IDM_OPTIONS_TURBO_A             40045
#define IDM_OPTIONS_TURBO_B             40046
#define IDM_OPTIONS_PAL                 40048
#define IDM_OPTIONS_FORCEPAL            40048
#define ID_BUTTON40050                  40050
#define ID_BUTTON40051                  40051
#define ID_BUTTON40052                  40052
#define ID_BUTTON40054                  40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40056
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
